### model
model_name_or_path: mistralai/Mistral-7B-v0.3
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z2_config.json
use_fast_tokenizer: true
flash_attn: fa2

### dataset
dataset: MiddOptimized-mistral_wizardlm
template: default
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/Mistral-7B-v0.3-Middo-WizardLM
save_only_model: true
logging_steps: 5
save_strategy: epoch
save_total_limit: 1
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 2.0e-5
use_liger_kernel: true
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000
